jina-ai/dev-gpt

- README.md
This layout gives a better overview over the examples. Less scrolling - more fun
> docs: tabular layout

- src/apis/gpt.py
I added a headline as per my knowledge, please let me know if any specific headline should be displayed, like user or system
> added missing headline variable while calling print_colored function

- .gitignore
- setup.py
- src/__init__.py
- src/apis/jina_cloud.py
- src/options/generate/generator.py
- src/options/generate/templates_system.py
- src/options/generate/templates_user.py
Since http is more common we dropped grpc and start using http
> feat: http instead of grpc

- src/apis/gpt.py
- src/apis/jina_cloud.py
- src/options/__init__.py
- src/options/generate/generator.py
- src/options/generate/static_files/gateway/Dockerfile
- src/options/generate/static_files/gateway/app_config.toml
- src/options/generate/static_files/gateway/custom_gateway.py
- src/options/generate/static_files/gateway/nginx.conf
- src/options/generate/static_files/gateway/requirements.txt
- src/options/generate/templates_user.py
Runs locally in the browser:
Runs on jcloud:
> Feat playground gateway

- src/apis/gpt.py
- src/apis/jina_cloud.py
- src/cli.py
Better error message when key is not there
> ℹ refactor: better key info

- src/options/generate/templates_user.py
let the user find the repo when they get the playground
> feat: put link to repo in the playground

- README.md
- src/options/generate/generator.py
- src/options/generate/templates_user.py
This allows the user to easily integrate the microservice into their app.
local curl:
online:
> 💻 feat: example code in playground

- requirements.txt
- src/apis/jina_cloud.py
- src/options/generate/generator.py
when pushing to the hub it can happen that you never get a response. In that case timing out and retrying sounds like a good idea. the retry time is 10 min
> fix: timeout error hub  push

- src/options/generate/templates_user.py
The string was broken and not formatted
> 🌏 fix: http remote

- setup.py
- src/__init__.py
- src/options/__init__.py
Users had hidden files that caused problems when listing files
Serving works as shown here:
> 🕵 fix: hidden files

- src/options/__init__.py
can not expect / but also need to consider \
> 🛣 fix: paths windows

- src/apis/jina_cloud.py
- src/utils/io.py
Improves:
- checking if docker is running
- error message when docker isn't reachable
> fix: is docker running

- src/apis/gpt.py
- src/cli.py
- src/options/__init__.py
- src/options/generate/generator.py
- src/options/generate/static_files/microservice/Dockerfile
- src/options/generate/templates_user.py
Closes #47. Uses Dockerfile template and only asks GPT to generate necessary `apt-get` packages. Adapts error handling accordingly.
> :safety_vest: feat: use dockerfile template

- README.md
- src/options/generate/generator.py
fix the content extraction from the content generated by the agent.
It is currently mixing microservice.py and test_microservice.py
> ⭐ fix: content extraction

- src/apis/pypi.py
- test/unit/test_api.py
This pr makes the parsing of the requirements more tolerant
> 🖊 fix: requirements parsing error

- src/options/generate/generator.py
- test/unit/test_response_parsing.py
two test cases for the parsing function
> ✏ test: response parsing

- dev_gpt/apis/gpt.py
Only show costs on verbose mode to not distract the user too much.
> 💸 refactor: costs on verbose

- dev_gpt/apis/gpt.py
- dev_gpt/options/generate/pm/pm.py
- dev_gpt/options/generate/static_files/microservice/jina_wrapper.py
- dev_gpt/options/generate/templates_user.py
There is currently an error in the generation that does not allow to run the microservice. It has to do with JSON serialization. At the moment, we are trying to serialize non-serializable objects.
> 🏃 fix: run function

- .github/workflows/ci.yml
- dev_gpt/constants.py
- dev_gpt/options/generate/chains/auto_refine_description.py
- dev_gpt/options/generate/generator.py
- dev_gpt/options/generate/static_files/gateway/app_template.py
- dev_gpt/options/generate/templates_user.py
With gpt-3.5, the playground was often generated badly. Here, we introduce a template that helps the model by just filling in the gaps.
> ⚽ refactor: playground more stable generation

- requirements.txt
there is an issue with langchain and other packages
> ⛓ fix: langchain dependency issue

- dev_gpt/apis/gpt.py
- dev_gpt/options/generate/generator.py
- dev_gpt/options/generate/templates_user.py
system prompt is not needed for this.
saving the name locally is also not needed.
not required to have special formatting in the response.
> 🤏 refactor: simplify name
